language: cpp

compiler:
- gcc

jobs:
  include:
  - name: "all projects"


script:
    - cmake -H. -B_build
    - cmake --build _build


addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
